export const CHANGE_LOADING = 'CHANGE_LOADING'
export const GET_LOCATION = 'GET_LOCATION'
export const GET_PHONE = 'GET_PHONE'
export const GET_COMMON_DATA = 'GET_COMMON_DATA'
export const GET_CURRENT_LIST = 'GET_CURRENT_LIST'
export const GET_HISTORY_LIST = 'GET_HISTORY_LIST'
export const GET_TYPEIN_DATA = 'GET_TYPEIN_DATA'
export const CLEAR_TYPEIN_DATA = 'CLEAR_TYPEIN_DATA'
export const GET_DISPOSE_DATA = 'GET_DISPOSE_DATA'
export const CLEAR_DISPOSE_DATA = 'CLEAR_DISPOSE_DATA'
export const GET_CIRCUIT_DATA = 'GET_CIRCUIT_DATA'
export const CLEAR_CIRCUIT_DATA = 'CLEAR_CIRCUIT_DATA'
export const GET_REPORT_DATA = 'GET_REPORT_DATA'
export const CLEAR_REPORT_DATA = 'CLEAR_REPORT_DATA'

export const SET_SEARCH_LIST = 'SET_SEARCH_LIST'

export const REQUEST_GET_STATION = 'REQUEST_GET_STATION'
export const RECEIVE_GET_STATION = 'RECEIVE_GET_STATION'

export const GET_PRIVILEGES = 'GET_PRIVILEGES' 

export const GET_USERS= 'GET_USERS'

export const GET_MENU = 'GET_MENU'
